name: chinese-elvis
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#312577'
    - '#ffffff'
    - '#e1d239'
    - '#e04836'
    - '#3694b0'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
