name: chinese-elvis
favicon: null
layout_spectrum: 0.97714
typography_spectrum: 0.08911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5625
  lightness: 0.42596044880338013
  saturation: 0.9586844127625227
  rhythmicContrast: 0.10314629413187504
purpose: []
